import type { FighterDefinition, MoveDefinition } from "./types";

function move(
  definition: Partial<MoveDefinition> &
    Pick<MoveDefinition, "id" | "label" | "input" | "animation">,
): MoveDefinition {
  return {
    startup: 8,
    active: 4,
    recovery: 15,
    damage: 7,
    guardDamage: 2,
    hitStun: 18,
    blockStun: 10,
    knockback: 0.13,
    hitLevel: "MID",
    tracking: 0.6,
    cancelWindow: 7,
    hitStop: 5,
    reach: 1.3,
    width: 0.65,
    height: 1.25,
    power: 1,
    ...definition,
  };
}

const redMoves: Record<string, MoveDefinition> = {
  jab: move({
    id: "jab",
    label: "Ignition Jab",
    input: "P",
    animation: "punch",
    startup: 5,
    active: 3,
    recovery: 10,
    damage: 6,
    reach: 1.28,
    power: 0.7,
  }),
  straight: move({
    id: "straight",
    label: "Vector Straight",
    input: "→ + P",
    animation: "punch",
    startup: 8,
    active: 4,
    recovery: 15,
    damage: 11,
    reach: 1.55,
    width: 0.7,
    power: 1.1,
  }),
  backfist: move({
    id: "backfist",
    label: "Redline Backfist",
    input: "← + P",
    animation: "punch",
    startup: 10,
    active: 5,
    recovery: 18,
    damage: 14,
    hitStun: 24,
    reach: 1.5,
    power: 1.25,
  }),
  bodyBlow: move({
    id: "bodyBlow",
    label: "Core Breaker",
    input: "↓ + P",
    animation: "punch",
    startup: 9,
    active: 4,
    recovery: 17,
    damage: 12,
    hitLevel: "MID",
    hitStun: 23,
    reach: 1.34,
    power: 1.2,
  }),
  power: move({
    id: "power",
    label: "Overdrive Impact",
    input: "P + K",
    animation: "punch",
    startup: 17,
    active: 7,
    recovery: 25,
    damage: 24,
    guardDamage: 12,
    hitStun: 34,
    blockStun: 18,
    knockback: 0.28,
    hitStop: 10,
    reach: 1.78,
    width: 0.9,
    power: 2.2,
    knockdown: true,
  }),
  kick: move({
    id: "kick",
    label: "Forge Kick",
    input: "K",
    animation: "kick",
    startup: 9,
    active: 5,
    recovery: 17,
    damage: 9,
    reach: 1.58,
    width: 0.72,
    power: 1,
  }),
  lowKick: move({
    id: "lowKick",
    label: "Heel Spark",
    input: "↓ + K",
    animation: "kick",
    startup: 8,
    active: 5,
    recovery: 14,
    damage: 8,
    hitLevel: "LOW",
    reach: 1.5,
    height: 0.42,
    power: 0.9,
  }),
  risingKick: move({
    id: "risingKick",
    label: "Rising Flare",
    input: "↑ + K",
    animation: "kick",
    startup: 12,
    active: 5,
    recovery: 22,
    damage: 16,
    hitStun: 30,
    reach: 1.48,
    power: 1.45,
    launcher: true,
  }),
  dashKick: move({
    id: "dashKick",
    label: "Crimson Drive",
    input: "→ → + K",
    animation: "kick",
    startup: 13,
    active: 6,
    recovery: 21,
    damage: 18,
    hitStun: 28,
    knockback: 0.22,
    hitStop: 8,
    reach: 1.86,
    width: 0.9,
    power: 1.7,
    knockdown: true,
  }),
  throw: move({
    id: "throw",
    label: "Breaker Throw",
    input: "K + G",
    animation: "throw",
    startup: 5,
    active: 3,
    recovery: 23,
    damage: 20,
    guardDamage: 0,
    hitLevel: "THROW",
    hitStun: 40,
    knockback: 0.35,
    hitStop: 8,
    reach: 1.08,
    width: 0.7,
    height: 1.6,
    power: 1.9,
    knockdown: true,
  }),
  counter: move({
    id: "counter",
    label: "Iron Counter",
    input: "P + G",
    animation: "punch",
    startup: 7,
    active: 5,
    recovery: 18,
    damage: 13,
    hitStun: 26,
    reach: 1.38,
    power: 1.35,
  }),
};

const blueMoves: Record<string, MoveDefinition> = {
  jab: move({
    id: "jab",
    label: "Pulse Tap",
    input: "P",
    animation: "punch",
    startup: 4,
    active: 3,
    recovery: 9,
    damage: 5,
    reach: 1.22,
    power: 0.65,
  }),
  straight: move({
    id: "straight",
    label: "Blue Shift",
    input: "→ + P",
    animation: "punch",
    startup: 7,
    active: 4,
    recovery: 13,
    damage: 9,
    reach: 1.48,
    power: 0.95,
  }),
  backfist: move({
    id: "backfist",
    label: "Mirror Check",
    input: "← + P",
    animation: "punch",
    startup: 8,
    active: 5,
    recovery: 16,
    damage: 12,
    hitStun: 24,
    reach: 1.42,
    power: 1.2,
  }),
  bodyBlow: move({
    id: "bodyBlow",
    label: "Kinetic Palm",
    input: "↓ + P",
    animation: "punch",
    startup: 7,
    active: 4,
    recovery: 15,
    damage: 10,
    hitStun: 22,
    reach: 1.28,
    power: 1.1,
  }),
  power: move({
    id: "power",
    label: "Blue Nova",
    input: "P + K",
    animation: "punch",
    startup: 15,
    active: 6,
    recovery: 23,
    damage: 20,
    guardDamage: 10,
    hitStun: 31,
    blockStun: 16,
    knockback: 0.25,
    hitStop: 9,
    reach: 1.7,
    width: 0.86,
    power: 2,
    knockdown: true,
  }),
  kick: move({
    id: "kick",
    label: "Arc Kick",
    input: "K",
    animation: "kick",
    startup: 7,
    active: 5,
    recovery: 14,
    damage: 8,
    reach: 1.5,
    width: 0.7,
    power: 0.95,
  }),
  lowKick: move({
    id: "lowKick",
    label: "Low Vector",
    input: "↓ + K",
    animation: "kick",
    startup: 6,
    active: 5,
    recovery: 12,
    damage: 7,
    hitLevel: "LOW",
    reach: 1.46,
    height: 0.4,
    power: 0.85,
  }),
  risingKick: move({
    id: "risingKick",
    label: "Skyline Lift",
    input: "↑ + K",
    animation: "kick",
    startup: 10,
    active: 6,
    recovery: 20,
    damage: 14,
    hitStun: 28,
    reach: 1.44,
    power: 1.35,
    launcher: true,
  }),
  dashKick: move({
    id: "dashKick",
    label: "Blue Comet",
    input: "→ → + K",
    animation: "kick",
    startup: 10,
    active: 6,
    recovery: 19,
    damage: 16,
    hitStun: 27,
    knockback: 0.2,
    hitStop: 8,
    reach: 1.8,
    width: 0.86,
    power: 1.6,
    knockdown: true,
  }),
  throw: move({
    id: "throw",
    label: "Orbit Throw",
    input: "K + G",
    animation: "throw",
    startup: 5,
    active: 3,
    recovery: 21,
    damage: 18,
    guardDamage: 0,
    hitLevel: "THROW",
    hitStun: 38,
    knockback: 0.32,
    hitStop: 8,
    reach: 1.06,
    width: 0.68,
    height: 1.6,
    power: 1.8,
    knockdown: true,
  }),
  counter: move({
    id: "counter",
    label: "Prism Counter",
    input: "P + G",
    animation: "punch",
    startup: 6,
    active: 5,
    recovery: 16,
    damage: 11,
    hitStun: 25,
    reach: 1.32,
    power: 1.25,
  }),
};

export const FIGHTER_DEFINITIONS: Record<string, FighterDefinition> = {
  red: {
    id: "red",
    name: "KAIRO",
    callsign: "THE FORGE VECTOR",
    archetype: "POWER",
    colors: {
      primary: 0xe62d42,
      secondary: 0x101522,
      accent: 0xffb23e,
      skin: 0xc8856d,
      hair: 0x11131d,
      glow: 0xff465b,
    },
    body: {
      height: 1.02,
      shoulderWidth: 1.08,
      chestDepth: 0.55,
      waistWidth: 0.64,
      hipWidth: 0.78,
      armLength: 0.93,
      legLength: 1.2,
      muscle: 1.12,
      headWidth: 0.92,
      jawWidth: 0.82,
      handScale: 1.08,
      footScale: 1.14,
    },
    moves: redMoves,
  },
  blue: {
    id: "blue",
    name: "SERA",
    callsign: "THE PRISM CURRENT",
    archetype: "SPEED",
    colors: {
      primary: 0x286dff,
      secondary: 0x0d1320,
      accent: 0x66efff,
      skin: 0xd59b84,
      hair: 0x101a2b,
      glow: 0x55e7ff,
    },
    body: {
      height: 0.98,
      shoulderWidth: 0.88,
      chestDepth: 0.48,
      waistWidth: 0.56,
      hipWidth: 0.76,
      armLength: 0.9,
      legLength: 1.28,
      muscle: 0.96,
      headWidth: 0.9,
      jawWidth: 0.78,
      handScale: 0.96,
      footScale: 1.02,
      longPanels: true,
    },
    moves: blueMoves,
  },
};

export const MOVE_ORDER = [
  "jab",
  "straight",
  "backfist",
  "bodyBlow",
  "power",
  "kick",
  "lowKick",
  "risingKick",
  "dashKick",
  "throw",
  "counter",
] as const;
