import { FIGHTER_DEFINITIONS } from "./definitions";
import type { FighterDefinition, MoveDefinition } from "./types";

export const AXION_FIGHTER_ID = "amber" as const;

function tuned(
  source: MoveDefinition,
  overrides: Partial<MoveDefinition> & Pick<MoveDefinition, "label">,
): MoveDefinition {
  return { ...source, ...overrides };
}

const red = FIGHTER_DEFINITIONS.red;
const blue = FIGHTER_DEFINITIONS.blue;

const axionMoves: Record<string, MoveDefinition> = {
  jab: tuned(red.moves.jab, {
    label: "Mass Check",
    startup: 6,
    recovery: 11,
    damage: 7,
    guardDamage: 3,
    reach: 1.36,
    power: 0.8,
  }),
  straight: tuned(red.moves.straight, {
    label: "Gravity Lance",
    startup: 10,
    active: 4,
    recovery: 17,
    damage: 12,
    guardDamage: 5,
    hitStun: 23,
    reach: 1.72,
    width: 0.72,
    power: 1.18,
  }),
  backfist: tuned(red.moves.backfist, {
    label: "Anchor Backhand",
    startup: 12,
    active: 5,
    recovery: 20,
    damage: 15,
    guardDamage: 6,
    hitStun: 26,
    knockback: 0.18,
    reach: 1.62,
    power: 1.38,
  }),
  bodyBlow: tuned(red.moves.bodyBlow, {
    label: "Core Compression",
    startup: 10,
    active: 5,
    recovery: 19,
    damage: 14,
    guardDamage: 8,
    hitStun: 26,
    blockStun: 14,
    knockback: 0.17,
    reach: 1.46,
    width: 0.78,
    power: 1.36,
  }),
  power: tuned(red.moves.power, {
    label: "Event Horizon",
    startup: 20,
    active: 7,
    recovery: 28,
    damage: 25,
    guardDamage: 16,
    hitStun: 36,
    blockStun: 20,
    knockback: 0.32,
    hitStop: 11,
    reach: 1.90,
    width: 0.98,
    power: 2.35,
  }),
  kick: tuned(red.moves.kick, {
    label: "Pillar Kick",
    startup: 10,
    active: 5,
    recovery: 19,
    damage: 10,
    guardDamage: 4,
    reach: 1.64,
    width: 0.78,
    power: 1.08,
  }),
  lowKick: tuned(red.moves.lowKick, {
    label: "Foundation Sweep",
    startup: 10,
    active: 5,
    recovery: 17,
    damage: 9,
    guardDamage: 5,
    hitStun: 21,
    reach: 1.62,
    width: 0.8,
    power: 1.02,
  }),
  risingKick: tuned(red.moves.risingKick, {
    label: "Lift Column",
    startup: 14,
    active: 5,
    recovery: 24,
    damage: 17,
    guardDamage: 7,
    hitStun: 31,
    reach: 1.58,
    power: 1.52,
  }),
  dashKick: tuned(red.moves.dashKick, {
    label: "Siege Vector",
    startup: 15,
    active: 6,
    recovery: 24,
    damage: 20,
    guardDamage: 10,
    hitStun: 30,
    knockback: 0.27,
    hitStop: 9,
    reach: 1.98,
    width: 0.94,
    power: 1.88,
  }),
  throw: tuned(red.moves.throw, {
    label: "Gravity Well",
    startup: 6,
    active: 3,
    recovery: 25,
    damage: 22,
    hitStun: 42,
    knockback: 0.40,
    hitStop: 9,
    reach: 1.14,
    width: 0.74,
    power: 2.04,
  }),
  counter: tuned(blue.moves.counter, {
    label: "Mass Reversal",
    startup: 9,
    active: 5,
    recovery: 20,
    damage: 15,
    guardDamage: 5,
    hitStun: 28,
    knockback: 0.18,
    reach: 1.46,
    power: 1.48,
  }),
};

export const AXION_FIGHTER_DEFINITION: FighterDefinition = Object.freeze({
  id: AXION_FIGHTER_ID,
  name: "AXION",
  callsign: "THE GRAVITY WARDEN",
  archetype: "POWER",
  colors: {
    primary: 0xd77a25,
    secondary: 0x111318,
    accent: 0xf2c35f,
    skin: 0xc99375,
    hair: 0x1b1715,
    glow: 0xffa947,
  },
  body: {
    height: 1.05,
    shoulderWidth: 1.13,
    clavicleWidth: 1.2,
    chestWidth: 1.08,
    chestDepth: 0.60,
    waistWidth: 0.68,
    pelvisWidth: 0.88,
    hipWidth: 0.82,
    armLength: 0.98,
    upperArmMass: 1.22,
    forearmMass: 1.18,
    legLength: 1.18,
    thighMass: 1.2,
    calfMass: 1.14,
    neckLength: 0.27,
    muscle: 1.18,
    headWidth: 0.94,
    headDepth: 0.89,
    jawWidth: 0.88,
    cheekWidth: 0.92,
    browDepth: 1.10,
    noseLength: 1.02,
    handScale: 1.12,
    footScale: 1.16,
  },
  moves: axionMoves,
});

export function registerAxionFighter(): FighterDefinition {
  FIGHTER_DEFINITIONS[AXION_FIGHTER_ID] = AXION_FIGHTER_DEFINITION;
  return AXION_FIGHTER_DEFINITION;
}
