import { FIGHTER_DEFINITIONS } from "./definitions";
import type { FighterDefinition, MoveDefinition } from "./types";

export const BRONT_FIGHTER_ID = "amber" as const;

function tuned(
  source: MoveDefinition,
  overrides: Partial<MoveDefinition> & Pick<MoveDefinition, "label">,
): MoveDefinition {
  return { ...source, ...overrides };
}

const red = FIGHTER_DEFINITIONS.red;
const blue = FIGHTER_DEFINITIONS.blue;

const brontMoves: Record<string, MoveDefinition> = {
  jab: tuned(red.moves.jab, {
    label: "Hammer Check",
    startup: 7,
    recovery: 12,
    damage: 8,
    guardDamage: 4,
    hitStun: 18,
    reach: 1.30,
    power: 0.92,
  }),
  straight: tuned(red.moves.straight, {
    label: "Piston Line",
    startup: 10,
    recovery: 17,
    damage: 14,
    guardDamage: 7,
    hitStun: 25,
    blockStun: 15,
    knockback: 0.18,
    reach: 1.62,
    width: 0.72,
    power: 1.38,
  }),
  backfist: tuned(red.moves.backfist, {
    label: "Bulkhead Rake",
    startup: 13,
    recovery: 21,
    damage: 16,
    guardDamage: 8,
    hitStun: 28,
    knockback: 0.22,
    reach: 1.50,
    width: 0.82,
    power: 1.56,
  }),
  bodyBlow: tuned(red.moves.bodyBlow, {
    label: "Gravity Ram",
    startup: 11,
    recovery: 19,
    damage: 16,
    guardDamage: 9,
    hitStun: 30,
    blockStun: 17,
    knockback: 0.20,
    reach: 1.40,
    width: 0.82,
    power: 1.62,
  }),
  power: tuned(red.moves.power, {
    label: "Mass Driver",
    startup: 20,
    active: 8,
    recovery: 29,
    damage: 27,
    guardDamage: 16,
    hitStun: 38,
    blockStun: 22,
    knockback: 0.36,
    reach: 1.80,
    width: 1.00,
    power: 2.58,
  }),
  kick: tuned(red.moves.kick, {
    label: "Anchor Kick",
    startup: 11,
    recovery: 19,
    damage: 12,
    guardDamage: 6,
    hitStun: 23,
    knockback: 0.16,
    reach: 1.58,
    power: 1.22,
  }),
  lowKick: tuned(red.moves.lowKick, {
    label: "Foundation Cut",
    startup: 10,
    recovery: 17,
    damage: 11,
    guardDamage: 6,
    hitStun: 22,
    reach: 1.57,
    width: 0.80,
    power: 1.18,
  }),
  risingKick: tuned(blue.moves.risingKick, {
    label: "Lift Column",
    startup: 15,
    recovery: 25,
    damage: 18,
    guardDamage: 8,
    hitStun: 31,
    knockback: 0.24,
    reach: 1.47,
    power: 1.72,
  }),
  dashKick: tuned(red.moves.dashKick, {
    label: "Freight Rush",
    startup: 16,
    recovery: 25,
    damage: 20,
    guardDamage: 10,
    hitStun: 31,
    knockback: 0.28,
    reach: 1.94,
    width: 0.90,
    power: 1.96,
  }),
  throw: tuned(red.moves.throw, {
    label: "Deadweight Drop",
    startup: 7,
    recovery: 27,
    damage: 23,
    hitStun: 42,
    knockback: 0.40,
    power: 2.18,
  }),
  counter: tuned(red.moves.counter, {
    label: "Load Bearing",
    startup: 8,
    active: 6,
    recovery: 20,
    damage: 15,
    guardDamage: 7,
    hitStun: 30,
    knockback: 0.22,
    reach: 1.42,
    power: 1.62,
  }),
};

export const BRONT_FIGHTER_DEFINITION: FighterDefinition = Object.freeze({
  id: BRONT_FIGHTER_ID,
  name: "BRONT",
  callsign: "THE GRAVITY FIST",
  archetype: "POWER",
  colors: {
    primary: 0xd58b2d,
    secondary: 0x111217,
    accent: 0xc8d0d8,
    skin: 0xb98265,
    hair: 0x17191c,
    glow: 0xffb64d,
  },
  body: {
    height: 1.05,
    shoulderWidth: 1.16,
    clavicleWidth: 1.12,
    chestWidth: 1.14,
    chestDepth: 0.62,
    waistWidth: 0.72,
    pelvisWidth: 0.94,
    hipWidth: 0.91,
    armLength: 1.02,
    upperArmMass: 1.18,
    forearmMass: 1.20,
    legLength: 1.12,
    thighMass: 1.14,
    calfMass: 1.11,
    neckLength: 0.22,
    muscle: 1.20,
    headWidth: 0.96,
    headDepth: 0.92,
    jawWidth: 0.96,
    cheekWidth: 0.93,
    browDepth: 1.10,
    noseLength: 1.02,
    handScale: 1.14,
    footScale: 1.14,
  },
  moves: brontMoves,
});

export function registerBrontFighter(): FighterDefinition {
  FIGHTER_DEFINITIONS[BRONT_FIGHTER_ID] = BRONT_FIGHTER_DEFINITION;
  return BRONT_FIGHTER_DEFINITION;
}
