"use client";

import { installRivalCircuitAiRuntime } from "@/src/game/rival-circuit-ai";
import { installRivalCircuitApexBossRuntime } from "@/src/game/rival-circuit-apex-boss";
import { installRivalCircuitArenaPresentation } from "@/src/game/rival-circuit-arena";
import { installRivalCircuitProtocolRuntime } from "@/src/game/rival-circuit-protocol-runtime";
import { installTpsArenaSpectaclePresentation } from "@/src/game/tps-arena-spectacle";
import { installTpsAttackActionHandoffPresentation } from "@/src/game/tps-attack-action-handoff";
import { installTpsBackfistSweepBoostPresentation } from "@/src/game/tps-backfist-sweep-boost";
import { installTpsBodyBlowLevelChangePresentation } from "@/src/game/tps-bodyblow-level-change";
import { installTpsCloseNeutralLanePresentation } from "@/src/game/tps-close-neutral-lane";
import { installTpsClosePunchLanePresentation } from "@/src/game/tps-close-punch-lane";
import { installTpsCounterSlipBoostPresentation } from "@/src/game/tps-counter-slip-boost";
import { installTpsCounterattackHandoffPresentation } from "@/src/game/tps-counterattack-handoff";
import { installTpsDashKickGroundContactPresentation } from "@/src/game/tps-dashkick-ground-contact";
import { installTpsFinalImpactVfxReadability } from "@/src/game/tps-final-impact-vfx-readability";
import { installTpsFrontKickOpenLinePresentation } from "@/src/game/tps-frontkick-open-line";
import { installTpsGroundingReadabilityPresentation } from "@/src/game/tps-grounding-readability";
import { installTpsGuardClashPresentation } from "@/src/game/tps-guard-clash";
import { installTpsImpactBeatSyncPresentation } from "@/src/game/tps-impact-beat-sync";
import { installTpsImpactFollowthroughPresentation } from "@/src/game/tps-impact-followthrough";
import { installTpsImpactLensPulsePresentation } from "@/src/game/tps-impact-lens-pulse";
import { installTpsInterceptSilhouettePresentation } from "@/src/game/tps-intercept-silhouette";
import { installTpsKickContactShapingPresentation } from "@/src/game/tps-kick-contact-shaping";
import { installTpsKickPairSpacingPresentation } from "@/src/game/tps-kick-pair-spacing";
import { installTpsKickSupportFootPresentation } from "@/src/game/tps-kick-support-foot";
import { installTpsLatestImpactWavePresentation } from "@/src/game/tps-latest-impact-wave";
import { installTpsLowKickOpenLinePresentation } from "@/src/game/tps-lowkick-open-line";
import { installTpsPowerBodyDrivePresentation } from "@/src/game/tps-power-body-drive";
import { installTpsPunishReadyPresentation } from "@/src/game/tps-punish-ready";
import { installTpsQuickstepBodyPresentation } from "@/src/game/tps-quickstep-body";
import { installTpsTelegraphHandoffPresentation } from "@/src/game/tps-telegraph-handoff";
import { installTpsThrowStagingPresentation } from "@/src/game/tps-throw-staging";

installRivalCircuitAiRuntime();
installRivalCircuitProtocolRuntime();
installRivalCircuitApexBossRuntime();
installTpsArenaSpectaclePresentation();
installRivalCircuitArenaPresentation();
installTpsGroundingReadabilityPresentation();
installTpsGuardClashPresentation();
installTpsThrowStagingPresentation();
installTpsQuickstepBodyPresentation();
installTpsTelegraphHandoffPresentation();
installTpsPunishReadyPresentation();
installTpsInterceptSilhouettePresentation();
installTpsBodyBlowLevelChangePresentation();
installTpsBackfistSweepBoostPresentation();
installTpsCounterSlipBoostPresentation();
installTpsImpactFollowthroughPresentation();
installTpsFrontKickOpenLinePresentation();
installTpsPowerBodyDrivePresentation();
installTpsLowKickOpenLinePresentation();
installTpsCloseNeutralLanePresentation();
installTpsClosePunchLanePresentation();
installTpsLatestImpactWavePresentation();
installTpsFinalImpactVfxReadability();
installTpsImpactLensPulsePresentation();
installTpsImpactBeatSyncPresentation();
installTpsCounterattackHandoffPresentation();
installTpsAttackActionHandoffPresentation();
installTpsKickContactShapingPresentation();
installTpsKickSupportFootPresentation();
installTpsDashKickGroundContactPresentation();
installTpsKickPairSpacingPresentation();

export default function TpsPresentationBootstrap() {
  return null;
}
